"use strict";
var hospital;
(function (hospital) {
    var p = new hospital.Paciente();
    p.setNome("David");
    p.setCpf("001.001.001-01");
    p.setCodPaciente(1);
    var p1 = new hospital.Paciente();
    p1.setNome("Zika");
    p1.setCpf("002.002.002-02");
    p1.setCodPaciente(2);
    var p2 = new hospital.Paciente();
    p2.setNome("Ronaldinho");
    p2.setCpf("003.003.003-03");
    p2.setCodPaciente(3);
    var e = new hospital.Enfermeiro();
    e.setNome("Pica Pau");
    e.setCpf("111.111.111-11");
    e.setCodFuncionario(1);
    e.setcoren(11);
    var e1 = new hospital.Enfermeiro();
    e1.setNome("Taz");
    e1.setCpf("222.222.222-22");
    e1.setCodFuncionario(3);
    e1.setcoren(12);
    var e2 = new hospital.Enfermeiro();
    e2.setNome("Pernalonga");
    e2.setCpf("333.333.333-33");
    e2.setCodFuncionario(3);
    e2.setcoren(13);
    var m = new hospital.Medico();
    m.setNome("Zeka Urubu");
    m.setespecialidade("Operações");
    m.setCrm(123);
    m.setCpf("123.123.123-11");
    m.setCodFuncionario(21);
    var m1 = new hospital.Medico();
    m1.setNome("Pernalonga");
    m1.setespecialidade("Ortopedista");
    m1.setCrm(456);
    m1.setCpf("123.123.123-12");
    m1.setCodFuncionario(22);
    var m2 = new hospital.Medico();
    m2.setNome("Pateta");
    m2.setespecialidade("Pediatra");
    m2.setCrm(789);
    m2.setCpf("123.123.123-13");
    m2.setCodFuncionario(23);
    var h = new hospital.Hospital();
    h.setnome("Hospital Daora");
    h.addEnfermeiros(e);
    h.addEnfermeiros(e1);
    h.addEnfermeiros(e2);
    h.addMedicos(m);
    h.addMedicos(m1);
    h.addMedicos(m2);
    h.addPacientes(p);
    h.addPacientes(p1);
    h.addPacientes(p2);
    document.getElementById("hospital").textContent = h.getnome();
    var tbMedico = document.getElementById("tbMedico");
    h.getmedicos().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var crm = h.getCrm();
        var especialidade = h.getEspecialidade();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + crm + "</td><td>" + especialidade + "</td></tr>";
        tbMedico.innerHTML += html;
    });
    var tbEnfermeiras = document.getElementById("tbEnfermeiras");
    h.getEnfermeiros().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var corem = h.getcoren();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + corem + "</td></tr>";
        tbEnfermeiras.innerHTML += html;
    });
    var tbPacientes = document.getElementById("tbPacientes");
    h.getpacientes().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var cod = h.getCodPaciente();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + cod + "</td></tr>";
        tbPacientes.innerHTML += html;
    });
})(hospital || (hospital = {}));
